name: Archived MAL Reviews

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run Scraping Script
      run: |
        chmod +x scripts/run.sh
        source .venv/bin/activate
        ./scripts/run.sh

    - name: Building Preview Page
      run: |
        chmod +x scripts/run.sh
        ./scripts/deploy.sh

    - name: Update Archive Branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
